dir: mocks/{{ replaceAll .PackagePath "internal" "src" }}
resolve-type-alias: false
issue-845-fix: true
packages:
  todo_list/internal/domain:
    config:
      all: true
      disable-version-string: true
      recursive: true
      with-expecter: true

