// Code generated by mockery. DO NOT EDIT.

package domain

import (
	context "context"
	domain "todo_list/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockListInterface is an autogenerated mock type for the ListInterface type
type MockListInterface struct {
	mock.Mock
}

type MockListInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockListInterface) EXPECT() *MockListInterface_Expecter {
	return &MockListInterface_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockListInterface) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockListInterface_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockListInterface_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockListInterface_Expecter) Close() *MockListInterface_Close_Call {
	return &MockListInterface_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockListInterface_Close_Call) Run(run func()) *MockListInterface_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockListInterface_Close_Call) Return(_a0 error) *MockListInterface_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockListInterface_Close_Call) RunAndReturn(run func() error) *MockListInterface_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: _a0, _a1
func (_m *MockListInterface) Create(_a0 context.Context, _a1 domain.List) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.List) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockListInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockListInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 domain.List
func (_e *MockListInterface_Expecter) Create(_a0 interface{}, _a1 interface{}) *MockListInterface_Create_Call {
	return &MockListInterface_Create_Call{Call: _e.mock.On("Create", _a0, _a1)}
}

func (_c *MockListInterface_Create_Call) Run(run func(_a0 context.Context, _a1 domain.List)) *MockListInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.List))
	})
	return _c
}

func (_c *MockListInterface_Create_Call) Return(_a0 error) *MockListInterface_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockListInterface_Create_Call) RunAndReturn(run func(context.Context, domain.List) error) *MockListInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockListInterface) Delete(_a0 context.Context, _a1 domain.UserID, _a2 domain.ListID) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserID, domain.ListID) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockListInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockListInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 domain.UserID
//   - _a2 domain.ListID
func (_e *MockListInterface_Expecter) Delete(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockListInterface_Delete_Call {
	return &MockListInterface_Delete_Call{Call: _e.mock.On("Delete", _a0, _a1, _a2)}
}

func (_c *MockListInterface_Delete_Call) Run(run func(_a0 context.Context, _a1 domain.UserID, _a2 domain.ListID)) *MockListInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.UserID), args[2].(domain.ListID))
	})
	return _c
}

func (_c *MockListInterface_Delete_Call) Return(_a0 error) *MockListInterface_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockListInterface_Delete_Call) RunAndReturn(run func(context.Context, domain.UserID, domain.ListID) error) *MockListInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: _a0, _a1
func (_m *MockListInterface) GetAll(_a0 context.Context, _a1 domain.UserID) ([]domain.List, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []domain.List
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserID) ([]domain.List, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserID) []domain.List); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.List)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.UserID) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockListInterface_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockListInterface_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 domain.UserID
func (_e *MockListInterface_Expecter) GetAll(_a0 interface{}, _a1 interface{}) *MockListInterface_GetAll_Call {
	return &MockListInterface_GetAll_Call{Call: _e.mock.On("GetAll", _a0, _a1)}
}

func (_c *MockListInterface_GetAll_Call) Run(run func(_a0 context.Context, _a1 domain.UserID)) *MockListInterface_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.UserID))
	})
	return _c
}

func (_c *MockListInterface_GetAll_Call) Return(_a0 []domain.List, _a1 error) *MockListInterface_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockListInterface_GetAll_Call) RunAndReturn(run func(context.Context, domain.UserID) ([]domain.List, error)) *MockListInterface_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: _a0, _a1
func (_m *MockListInterface) Update(_a0 context.Context, _a1 domain.List) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.List) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockListInterface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockListInterface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 domain.List
func (_e *MockListInterface_Expecter) Update(_a0 interface{}, _a1 interface{}) *MockListInterface_Update_Call {
	return &MockListInterface_Update_Call{Call: _e.mock.On("Update", _a0, _a1)}
}

func (_c *MockListInterface_Update_Call) Run(run func(_a0 context.Context, _a1 domain.List)) *MockListInterface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.List))
	})
	return _c
}

func (_c *MockListInterface_Update_Call) Return(_a0 error) *MockListInterface_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockListInterface_Update_Call) RunAndReturn(run func(context.Context, domain.List) error) *MockListInterface_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockListInterface creates a new instance of MockListInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockListInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockListInterface {
	mock := &MockListInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
